### ISSUE TITLE
week-4生成树的规则是什么？

### ISSUE THREAD

**Issue by liyufu** [nxintech/zqh#1]
week-4生成树的规则是什么？比如：3、2、4、7、1、5，6、8生成后是什么样？

**Comment by liuyangc3** [comment]
插入方式不限制

推荐从根节点进行插入，小于当前节点的值的放在左子树，大于的放在右子树，

这种方法构成的树和插入顺序有关
![graph](https://cloud.githubusercontent.com/assets/6705844/15036792/8a3a7b22-12c6-11e6-94c6-b006a21b4846.png)
